# Generated by Django 3.1.7 on 2021-03-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=200)),
                ('pname', models.CharField(max_length=200)),
                ('uemail', models.EmailField(max_length=200)),
                ('pword', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.TextField(max_length=700),
        ),
    ]
