# Generated by Django 3.1.7 on 2021-03-20 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210320_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Join',
        ),
    ]
