# Generated by Django 3.1.7 on 2021-03-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
