# Generated by Django 3.1.7 on 2021-04-05 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
