# Generated by Django 3.1.7 on 2021-04-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
